export const ActionType = {
    "INCREMENT" : "INCREMENT",
    "DECREMENT" : "DECREMENT",
    "TOGGLECONTENT" : "TOGGLECONTENT",
    "ADDPRODUCTINFO":"ADDPRODUCTINFO",
    "LOGGED_IN_USER":"LOGGED_IN_USER",
    "LOGOUT" : "LOGOUT"
}